format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$nodejs\
$cmd_duration $jobs $time\
$line_break\
$character"""

[nodejs]
format = "[$symbol($version )]($style)"

[fill]
symbol = " "

[directory]
style = "#d79921"
read_only = " "
truncation_length = 12
truncate_to_repo = false

[character]
success_symbol = "[❯](#d65d0e)"
error_symbol = "[❯](#cc241d)"
vicmd_symbol = "[❮](#98971a)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bright-black"

[jobs]
symbol = ""
style = "bold red"
number_threshold = 9
format = "[$symbol]($style)"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "#458588"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[cmd_duration]
format = "[$duration]($style)"
style = "#d65d0e"

[memory_usage]
symbol = " "

[rust]
symbol = " "

[time]
disabled = false
style = "bold #ebddb2"
format = "[$time]($style)"

[custom.stunnel]
when = "ps aux | grep stunnel | grep -v grep"
command = "ps -o etime= -p $(ps aux | grep stunnel | grep -v grep | awk '{print $10}')"
style = "red"
format = "[TUNNEL OPEN for $output]($style)"
