[window]
opacity=1	
blur=false

[font.normal]
family='JetBrainsMono Nerd Font'

[font]
size=12

[cursor]
style = "Beam"

[window.padding]
x = 6
y = 0

[colors.primary]
background = "#1d2021"
foreground = "#ebddb2"

[selection]
save_to_clipboard=true
